### ISSUE TITLE
RemotePlay on SteamLink(Android) do not recognize the gamepad while in game

### ISSUE THREAD

**Issue by usermx01** [hectorm/docker-steam#8]
First of all, thank you for this great approach to steam in docker. Works great for running on Windows RDP (do not know how to use a gamepad over RDP though). 

When I try to use it over SteamLink( on Android) I cannot get the gamepad to be recognized once the game starts. 

I run the docker-compose in Ubuntu 22.04 VM on Proxmox 7.2 with only three changes.
>1 added in  devices: - '/dev/uinput:/dev/uinput' (As I found in other issue rised here that was the solution)
>2 added in  security_opt:  - 'apparmor=unconfined' (For proton to work)
>3 added  volumes:  - '/media:/media' (For storing the games) 

Is there something else I need to do for the controller to be recognized while in the games ? I'm testing with brawhalla currently.

Another question, what is the best approach for setting the container to start steam automatically on each boot?

**Comment by usermx01** [comment]
After messing a lot with configuration running the steam client in windows do work using keyboard and mouse but not with joystick. O have given the container it's own lan IP and added some volumes just to make the steam config and games persistent after initial setup. 

My current compose looks like 
```
version: '3.9'
services:
  steam:
    image: 'docker.io/hectorm/steam:latest'
    shm_size: '2gb'
    security_opt:
      - 'label=type:spc_t'
      - 'seccomp=unconfined'
    privileged: true
    devices:
      - '/dev/dri:/dev/dri'
      - '/dev/uinput:/dev/uinput'
    volumes:
      - '/media/SteamLibrary:/media/SteamLibrary'
      - '/media/Steam/.local:/home/user/.local'
      - '/run/udev/:/run/udev/'
      - '/dev/input:/dev/input'
    mac_address: 02:42:c0:a8:84:23
    networks:
      - testVlan
   
networks:
 testVlan:
    driver: macvlan
    driver_opts:
      parent: enp6s19
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 192.168.5.0/24
          gateway: 192.168.5.1
          ip_range: 192.168.5.53/32
```

jstest can see the connected steam link joystick in /dev/inputs but won't work when pressing any buttons either, just like in normal games launched from steam's BPM or desktop.
